export const districtsInNepal = [
  'Achham',
  'Arghakhanchi',
  'Baglung',
  'Baitadi',
  'Bajhang',
  'Bajura',
  'Banke',
  'Bara',
  'Bardiya',
  'Bhaktapur',
  'Bhojpur',
  'Chitwan',
  'Dadeldhura',
  'Dailekh',
  'Dang',
  'Darchula',
  'Dhading',
  'Dhankuta',
  'Dhanusa',
  'Dholkha',
  'Dolpa',
  'Doti',
  'Eastern Rukum',
  'Gorkha',
  'Gulmi',
  'Humla',
  'Ilam',
  'Jajarkot',
  'Jhapa',
  'Jumla',
  'Kailali',
  'Kalikot',
  'Kanchanpur',
  'Kapilvastu',
  'Kaski',
  'Kathmandu',
  'Kavrepalanchok',
  'Khotang',
  'Lalitpur',
  'Lamjung',
  'Mahottari',
  'Makwanpur',
  'Manang',
  'Morang',
  'Mugu',
  'Mustang',
  'Myagdi',
  'Nawalparasi',
  'Nuwakot',
  'Okhaldhunga',
  'Palpa',
  'Panchthar',
  'Parasi',
  'Parbat',
  'Parsa',
  'Pyuthan',
  'Ramechhap',
  'Rasuwa',
  'Rautahat',
  'Rolpa',
  'Rukum',
  'Rupandehi',
  'Salyan',
  'Sankhuwasabha',
  'Saptari',
  'Sarlahi',
  'Sindhuli',
  'Sindhupalchok',
  'Siraha',
  'Solukhumbu',
  'Sunsari',
  'Surkhet',
  'Syangja',
  'Tanahun',
  'Taplejung',
  'Terhathum',
  'Udayapur',
  'Western Rukum'
];

export const districtsInNepalNepali = [
  "अछाम",
  "अर्घाखाँची",
  "बागलुङ",
  "बैतडी",
  "बझाङ",
  "बाजुरा",
  "बाँके",
  "बारा",
  "बर्दिया",
  "भक्तपुर",
  "भोजपुर",
  "चितवन",
  "दडेल्धुरा",
  "दैलेख",
  "दाङ",
  "दार्चुला",
  "धादिङ",
  "धनकुटा",
  "धनुषा",
  "धोलाकोट",
  "दोलखा",
  "डोल्पा",
  "डोटी",
  "पूर्वी रुकुम",
  "गोरखा",
  "गुल्मी",
  "हुम्ला",
  "इलाम",
  "जाजरकोट",
  "झापा",
  "जुम्ला",
  "कैलाली",
  "कालिकोट",
  "कञ्चनपुर",
  "कपिलवस्तु",
  "कास्की",
  "काठमाण्डौ",
  "काव्रेपलाञ्चोक",
  "खोटाङ",
  "ललितपुर",
  "लामजुङ",
  "महोत्तरी",
  "मकवानपुर",
  "मनाङ",
  "मोरङ",
  "मुगु",
  "मुस्ताङ",
  "म्याग्दी",
  "नवलपुर",
  "नुवाकोट",
  "ओखलढुङ्गा",
  "पाल्पा",
  "पाँचथर",
  "पर्वत",
  "पर्सा"
];


export const statesInNepal = [
  "Province No. 1",
  "Province No. 2",
  "Bagmati Province",
  "Gandaki Province",
  "Lumbini Province",
  "Karnali Province",
  "Sudurpashchim Province"
];
